{
 "title": "evidently",
 "time": { "from": "2022-02-01T00:00:00.000Z", "to": "2022-02-20T00:00:00.000Z" },
 "panels": [
  {
   "title": "Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\ntimestamp AS time,\r\nshare_missing_values\r\nFROM evidently_metrics\r\nWHERE $__timeFilter(timestamp) "
    }
   ]
  },
  {
   "title": "Num Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\ntimestamp AS time,\r\nnum_drifted_columns\r\nFROM evidently_metrics\r\nWHERE $__timeFilter(timestamp) "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\ntimestamp AS time,\r\nprediction_drift\r\nFROM evidently_metrics\r\nWHERE $__timeFilter(timestamp) "
    }
   ]
  }
 ]
}