name: CI Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - 'web_service/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # clones repo onto VM and install docker
      - name: Set up Python 3.13.3
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        working-directory: web_service/
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run Unit Tests
        working-directory: tests/
        run: pytest .

      - name: Lint
        working-directory: web_service/
        run: pylint --recursive=y .

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Integration Tests
        working-directory: web_service/integration-test/
        run: |
          . run.sh
